name: Publish MARIADB
on:
  push:
    branches:
      - main
    paths:
      - "mariadb/**"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/update@v4.25.1
        with:
          driver: com.mariadb.jdbc.Driver
          classpath: mariadb/lib/mariadb-connector-3.3.3.jar
          changelogFile: "changelog.xml"
          url: ${{ secrets.MYSQL_URL }}
          username: ${{ secrets.MYSQL_USERNAME }}
          password: ${{ secrets.MYSQL_PASSWORD }}
          searchPath: mariadb
