name: Rollback MARIADB

on:
  workflow_dispatch:
    inputs:
      count:
        type: string
        description: Changes rollback count
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/rollback-count@v4.25.1
        with:
          count: ${{ github.event.inputs.count }}
          driver: org.mariadb.jdbc.Driver
          classpath: mariadb/lib/mariadb-connector-3.3.3.jar
          changelogFile: "changelog.xml"
          url: ${{ secrets.MYSQL_URL }}
          username: ${{ secrets.MYSQL_USERNAME }}
          password: ${{ secrets.MYSQL_PASSWORD }}
          searchPath: mariadb
